<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Контакты");
$assets->addString('<meta name="robots" content="noindex, nofollow">');
$elems = $fixer->GetElements(array(), array("IBLOCK_ID"=>"4", "ACTIVE" => "Y"), false, false, array("ID", "IBLOCK_ID"));
$elId = $elems[0]["ID"];
?>
<?$APPLICATION->IncludeComponent("bitrix:news.detail", "contacts", Array(
	"ACTIVE_DATE_FORMAT" => "d.m.Y",
	"ADD_ELEMENT_CHAIN" => "N",
	"ADD_SECTIONS_CHAIN" => "N",
	"AJAX_MODE" => "N",
	"AJAX_OPTION_ADDITIONAL" => "",
	"AJAX_OPTION_HISTORY" => "N",
	"AJAX_OPTION_JUMP" => "N",
	"AJAX_OPTION_STYLE" => "N",
	"BROWSER_TITLE" => "-",
	"CACHE_GROUPS" => "Y",
	"CACHE_TIME" => "36000000",
	"CACHE_TYPE" => "A",
	"CHECK_DATES" => "Y",
	"DETAIL_URL" => "",
	"DISPLAY_BOTTOM_PAGER" => "N",
	"DISPLAY_DATE" => "N",
	"DISPLAY_NAME" => "N",
	"DISPLAY_PICTURE" => "N",
	"DISPLAY_PREVIEW_TEXT" => "N",
	"DISPLAY_TOP_PAGER" => "N",
	"ELEMENT_CODE" => "",
	"ELEMENT_ID" => $elId,
	"FIELD_CODE" => array(),
	"IBLOCK_ID" => "4",
	"IBLOCK_TYPE" => "pages",
	"IBLOCK_URL" => "",
	"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
	"MESSAGE_404" => "",
	"META_DESCRIPTION" => "-",
	"META_KEYWORDS" => "-",
	"PAGER_BASE_LINK_ENABLE" => "N",
	"PAGER_SHOW_ALL" => "N",
	"PAGER_TEMPLATE" => ".default",
	"PAGER_TITLE" => "Страница",
	"PROPERTY_CODE" => array(
		0 => "ADDRESS",
		1 => "PHONE_1",
		2 => "PHONE_2",
		3 => "WORK_TIME",
		4 => "REQUISITE",
	),
	"SET_BROWSER_TITLE" => "Y",
	"SET_CANONICAL_URL" => "N",
	"SET_LAST_MODIFIED" => "N",
	"SET_META_DESCRIPTION" => "N",
	"SET_META_KEYWORDS" => "N",
	"SET_STATUS_404" => "N",
	"SET_TITLE" => "N",
	"SHOW_404" => "N",
	"STRICT_SECTION_CHECK" => "N",
	"USE_PERMISSIONS" => "N",
	"USE_SHARE" => "N",
), false);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>